# Generated by Django 3.0.2 on 2020-02-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0002_admin_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='contractor_registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.IntegerField(blank='True', null='True')),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
