# Generated by Django 3.0.2 on 2020-02-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0004_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.IntegerField(blank='True', null='True')),
                ('type', models.CharField(max_length=200)),
                ('fromdate', models.CharField(max_length=200)),
                ('todate', models.CharField(max_length=200)),
                ('budget', models.CharField(max_length=200)),
                ('enumber', models.CharField(max_length=200)),
                ('contractor', models.CharField(max_length=200)),
            ],
        ),
    ]
