# Generated by Django 3.0.2 on 2020-02-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0005_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='status',
            field=models.CharField(default='pending', max_length=200),
        ),
    ]
