# Generated by Django 3.0.2 on 2020-02-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0006_work_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor_registration',
            name='status',
            field=models.CharField(default='Available', max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(default='Available', max_length=200),
        ),
    ]
