# Generated by Django 3.0 on 2020-02-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0007_auto_20200204_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='password',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='username',
        ),
        migrations.AddField(
            model_name='admin',
            name='eid',
            field=models.IntegerField(blank='True', null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='admin',
            name='wid',
            field=models.IntegerField(blank='True', null='True'),
            preserve_default='True',
        ),
    ]
