# Generated by Django 3.0 on 2020-02-05 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0008_auto_20200205_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='select_employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wid', models.IntegerField(blank='True', null='True')),
                ('eid', models.IntegerField(blank='True', null='True')),
            ],
        ),
        migrations.RemoveField(
            model_name='admin',
            name='eid',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='wid',
        ),
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
