# Generated by Django 3.0 on 2020-02-05 10:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0009_auto_20200205_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='select_employee',
            name='eid',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='select_employee',
            name='wid',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
